experiment 27 : catboost + dataset 2 + grid search

Traceback (most recent call last):
  File "node_2.py", line 11, in <module>
    dataset=reader_writer.baca_data_cus_seg(),
  File "/home/m448735/hyperparameter-tuning-benchmark/services/reader_writer.py", line 22, in baca_data_cus_seg
    X=np.genfromtxt(X_path, delimiter=',')
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: /home/m448735/hyperparameter-tuning-benchmark/dataset-ready/X_cus_seg.csv not found.
srun: error: komputasi06: task 0: Exited with exit code 1
