experiment 23 : lightgbm + dataset 2 + random search

Traceback (most recent call last):
  File "node_2.py", line 8, in <module>
    experiments.exp_random_search(
  File "/home/m448735/hyperparameter-tuning-benchmark/experiments.py", line 58, in exp_random_search
    hasil=opt.optimized_random_search(X,y,kwargs["model"],kwargs["hyperparameter"],seed,kwargs["eval_method"])
  File "/home/m448735/hyperparameter-tuning-benchmark/services/optimizer.py", line 50, in optimized_random_search
    search.fit(X,y)
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 654, in fit
    scorers, self.multimetric_ = _check_multimetric_scoring(
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 475, in _check_multimetric_scoring
    scorers = {"score": check_scoring(estimator, scoring=scoring)}
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 402, in check_scoring
    raise TypeError("estimator should be an estimator implementing "
TypeError: estimator should be an estimator implementing 'fit' method, <function lightgbm_model at 0x7fb9beb38af0> was passed
srun: error: komputasi06: task 0: Exited with exit code 1
